name: Build user config
on:
  push:
    paths:
      - "boards/**"
      - "config/**"
      - "zephyr/**"
      - build.yaml
  pull_request:
    paths:
      - "boards/**"
      - "config/**"
      - "zephyr/**"
      - build.yaml
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  draw-layout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pipx and dependecies
        uses: liskin/gh-pipx@v1
        with:
          packages: keymap-drawer

      - name: Run keymap and draw layout
        run: |
          keymap parse --columns 1 --zmk-keymap ./config/chocofi.keymap > mapping.yaml
          keymap draw mapping.yaml > ./images/layout.svg

      - name: Check if layout.svg changed
        id: check_diff
        run: |
          git diff --quiet ./images/layout.svg || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit laoyout
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add ./images/layout.svg
          git commit --message "docs: update layout.svg"
          git push origin ${{ github.head_ref || github.ref_name }}
